### ISSUE TITLE
 Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by xdlover** [Stevenzwzhai/plugs#2]
//在这里先循环子集，在与对应的父级匹配之后break;减少父级循环
        child.forEach(function(itemChild){ //这里的forEach报错了
            parent.forEach(function(itemParent){
                if(itemChild.fparentid == itemParent.faccountid){
                    itemParent.childs.push(itemChild);
                    break;
                }
            })
        })

**Comment by Stevenzwzhai** [comment]
已修改
