### ISSUE TITLE
ie8下光标总问题？

### ISSUE THREAD

**Issue by tzcodingjs** [Stevenzwzhai/plugs#3]
你好！ie8下的input的光标为什么总是在左侧，导致使用该方法不能有效获取光标位置。

**Comment by Stevenzwzhai** [comment]
这边有报错吗？我这边在ietest上测试只是document事件监听没有兼容报错

**Comment by tzcodingjs** [comment]
@Stevenzwzhai 问题已经解决了，谢谢！
